// @generated by protoc-gen-es v2.2.5 with parameter "target=ts"
// @generated from file todo/v1/todo.proto (package todo.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file todo/v1/todo.proto.
 */
export const file_todo_v1_todo: GenFile = /*@__PURE__*/
  fileDesc("ChJ0b2RvL3YxL3RvZG8ucHJvdG8SB3RvZG8udjEiYAoIVG9kb0l0ZW0SCgoCaWQYASABKAkSDQoFdGl0bGUYAiABKAkSEQoJY29tcGxldGVkGAMgASgIEhIKCmNyZWF0ZWRfYXQYBCABKAkSEgoKdXBkYXRlZF9hdBgFIAEoCSIiChFDcmVhdGVUb2RvUmVxdWVzdBINCgV0aXRsZRgBIAEoCSI1ChJDcmVhdGVUb2RvUmVzcG9uc2USHwoEaXRlbRgBIAEoCzIRLnRvZG8udjEuVG9kb0l0ZW0iHAoOR2V0VG9kb1JlcXVlc3QSCgoCaWQYASABKAkiMgoPR2V0VG9kb1Jlc3BvbnNlEh8KBGl0ZW0YASABKAsyES50b2RvLnYxLlRvZG9JdGVtImQKEExpc3RUb2Rvc1JlcXVlc3QSFwoKbmV4dF90b2tlbhgBIAEoCUgAiAEBEhgKC21heF9yZXN1bHRzGAIgASgFSAGIAQFCDQoLX25leHRfdG9rZW5CDgoMX21heF9yZXN1bHRzIl0KEUxpc3RUb2Rvc1Jlc3BvbnNlEiAKBWl0ZW1zGAEgAygLMhEudG9kby52MS5Ub2RvSXRlbRIXCgpuZXh0X3Rva2VuGAIgASgJSACIAQFCDQoLX25leHRfdG9rZW4iYwoRVXBkYXRlVG9kb1JlcXVlc3QSCgoCaWQYASABKAkSEgoFdGl0bGUYAiABKAlIAIgBARIWCgljb21wbGV0ZWQYAyABKAhIAYgBAUIICgZfdGl0bGVCDAoKX2NvbXBsZXRlZCI1ChJVcGRhdGVUb2RvUmVzcG9uc2USHwoEaXRlbRgBIAEoCzIRLnRvZG8udjEuVG9kb0l0ZW0iHwoRRGVsZXRlVG9kb1JlcXVlc3QSCgoCaWQYASABKAkiJQoSRGVsZXRlVG9kb1Jlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgy5AIKC1RvZG9TZXJ2aWNlEkUKCkNyZWF0ZVRvZG8SGi50b2RvLnYxLkNyZWF0ZVRvZG9SZXF1ZXN0GhsudG9kby52MS5DcmVhdGVUb2RvUmVzcG9uc2USPAoHR2V0VG9kbxIXLnRvZG8udjEuR2V0VG9kb1JlcXVlc3QaGC50b2RvLnYxLkdldFRvZG9SZXNwb25zZRJCCglMaXN0VG9kb3MSGS50b2RvLnYxLkxpc3RUb2Rvc1JlcXVlc3QaGi50b2RvLnYxLkxpc3RUb2Rvc1Jlc3BvbnNlEkUKClVwZGF0ZVRvZG8SGi50b2RvLnYxLlVwZGF0ZVRvZG9SZXF1ZXN0GhsudG9kby52MS5VcGRhdGVUb2RvUmVzcG9uc2USRQoKRGVsZXRlVG9kbxIaLnRvZG8udjEuRGVsZXRlVG9kb1JlcXVlc3QaGy50b2RvLnYxLkRlbGV0ZVRvZG9SZXNwb25zZWIGcHJvdG8z");

/**
 * TODOアイテムのメッセージ定義
 *
 * @generated from message todo.v1.TodoItem
 */
export type TodoItem = Message<"todo.v1.TodoItem"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: bool completed = 3;
   */
  completed: boolean;

  /**
   * @generated from field: string created_at = 4;
   */
  createdAt: string;

  /**
   * @generated from field: string updated_at = 5;
   */
  updatedAt: string;
};

/**
 * Describes the message todo.v1.TodoItem.
 * Use `create(TodoItemSchema)` to create a new message.
 */
export const TodoItemSchema: GenMessage<TodoItem> = /*@__PURE__*/
  messageDesc(file_todo_v1_todo, 0);

/**
 * TODOアイテムの作成リクエスト
 *
 * @generated from message todo.v1.CreateTodoRequest
 */
export type CreateTodoRequest = Message<"todo.v1.CreateTodoRequest"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;
};

/**
 * Describes the message todo.v1.CreateTodoRequest.
 * Use `create(CreateTodoRequestSchema)` to create a new message.
 */
export const CreateTodoRequestSchema: GenMessage<CreateTodoRequest> = /*@__PURE__*/
  messageDesc(file_todo_v1_todo, 1);

/**
 * TODOアイテムの作成レスポンス
 *
 * @generated from message todo.v1.CreateTodoResponse
 */
export type CreateTodoResponse = Message<"todo.v1.CreateTodoResponse"> & {
  /**
   * @generated from field: todo.v1.TodoItem item = 1;
   */
  item?: TodoItem;
};

/**
 * Describes the message todo.v1.CreateTodoResponse.
 * Use `create(CreateTodoResponseSchema)` to create a new message.
 */
export const CreateTodoResponseSchema: GenMessage<CreateTodoResponse> = /*@__PURE__*/
  messageDesc(file_todo_v1_todo, 2);

/**
 * TODOアイテムの取得リクエスト
 *
 * @generated from message todo.v1.GetTodoRequest
 */
export type GetTodoRequest = Message<"todo.v1.GetTodoRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message todo.v1.GetTodoRequest.
 * Use `create(GetTodoRequestSchema)` to create a new message.
 */
export const GetTodoRequestSchema: GenMessage<GetTodoRequest> = /*@__PURE__*/
  messageDesc(file_todo_v1_todo, 3);

/**
 * TODOアイテムの取得レスポンス
 *
 * @generated from message todo.v1.GetTodoResponse
 */
export type GetTodoResponse = Message<"todo.v1.GetTodoResponse"> & {
  /**
   * @generated from field: todo.v1.TodoItem item = 1;
   */
  item?: TodoItem;
};

/**
 * Describes the message todo.v1.GetTodoResponse.
 * Use `create(GetTodoResponseSchema)` to create a new message.
 */
export const GetTodoResponseSchema: GenMessage<GetTodoResponse> = /*@__PURE__*/
  messageDesc(file_todo_v1_todo, 4);

/**
 * TODOアイテムの一覧取得リクエスト
 *
 * @generated from message todo.v1.ListTodosRequest
 */
export type ListTodosRequest = Message<"todo.v1.ListTodosRequest"> & {
  /**
   * ページネーションのための開始キー（オプション）
   *
   * @generated from field: optional string next_token = 1;
   */
  nextToken?: string;

  /**
   * 1ページあたりの最大アイテム数（オプション）
   *
   * @generated from field: optional int32 max_results = 2;
   */
  maxResults?: number;
};

/**
 * Describes the message todo.v1.ListTodosRequest.
 * Use `create(ListTodosRequestSchema)` to create a new message.
 */
export const ListTodosRequestSchema: GenMessage<ListTodosRequest> = /*@__PURE__*/
  messageDesc(file_todo_v1_todo, 5);

/**
 * TODOアイテムの一覧取得レスポンス
 *
 * @generated from message todo.v1.ListTodosResponse
 */
export type ListTodosResponse = Message<"todo.v1.ListTodosResponse"> & {
  /**
   * @generated from field: repeated todo.v1.TodoItem items = 1;
   */
  items: TodoItem[];

  /**
   * 次のページがある場合の開始キー
   *
   * @generated from field: optional string next_token = 2;
   */
  nextToken?: string;
};

/**
 * Describes the message todo.v1.ListTodosResponse.
 * Use `create(ListTodosResponseSchema)` to create a new message.
 */
export const ListTodosResponseSchema: GenMessage<ListTodosResponse> = /*@__PURE__*/
  messageDesc(file_todo_v1_todo, 6);

/**
 * TODOアイテムの更新リクエスト
 *
 * @generated from message todo.v1.UpdateTodoRequest
 */
export type UpdateTodoRequest = Message<"todo.v1.UpdateTodoRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: optional string title = 2;
   */
  title?: string;

  /**
   * @generated from field: optional bool completed = 3;
   */
  completed?: boolean;
};

/**
 * Describes the message todo.v1.UpdateTodoRequest.
 * Use `create(UpdateTodoRequestSchema)` to create a new message.
 */
export const UpdateTodoRequestSchema: GenMessage<UpdateTodoRequest> = /*@__PURE__*/
  messageDesc(file_todo_v1_todo, 7);

/**
 * TODOアイテムの更新レスポンス
 *
 * @generated from message todo.v1.UpdateTodoResponse
 */
export type UpdateTodoResponse = Message<"todo.v1.UpdateTodoResponse"> & {
  /**
   * @generated from field: todo.v1.TodoItem item = 1;
   */
  item?: TodoItem;
};

/**
 * Describes the message todo.v1.UpdateTodoResponse.
 * Use `create(UpdateTodoResponseSchema)` to create a new message.
 */
export const UpdateTodoResponseSchema: GenMessage<UpdateTodoResponse> = /*@__PURE__*/
  messageDesc(file_todo_v1_todo, 8);

/**
 * TODOアイテムの削除リクエスト
 *
 * @generated from message todo.v1.DeleteTodoRequest
 */
export type DeleteTodoRequest = Message<"todo.v1.DeleteTodoRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message todo.v1.DeleteTodoRequest.
 * Use `create(DeleteTodoRequestSchema)` to create a new message.
 */
export const DeleteTodoRequestSchema: GenMessage<DeleteTodoRequest> = /*@__PURE__*/
  messageDesc(file_todo_v1_todo, 9);

/**
 * TODOアイテムの削除レスポンス
 *
 * @generated from message todo.v1.DeleteTodoResponse
 */
export type DeleteTodoResponse = Message<"todo.v1.DeleteTodoResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message todo.v1.DeleteTodoResponse.
 * Use `create(DeleteTodoResponseSchema)` to create a new message.
 */
export const DeleteTodoResponseSchema: GenMessage<DeleteTodoResponse> = /*@__PURE__*/
  messageDesc(file_todo_v1_todo, 10);

/**
 * TODOサービスの定義
 *
 * @generated from service todo.v1.TodoService
 */
export const TodoService: GenService<{
  /**
   * TODOアイテムを作成
   *
   * @generated from rpc todo.v1.TodoService.CreateTodo
   */
  createTodo: {
    methodKind: "unary";
    input: typeof CreateTodoRequestSchema;
    output: typeof CreateTodoResponseSchema;
  },
  /**
   * 特定のTODOアイテムを取得
   *
   * @generated from rpc todo.v1.TodoService.GetTodo
   */
  getTodo: {
    methodKind: "unary";
    input: typeof GetTodoRequestSchema;
    output: typeof GetTodoResponseSchema;
  },
  /**
   * TODOアイテムの一覧を取得
   *
   * @generated from rpc todo.v1.TodoService.ListTodos
   */
  listTodos: {
    methodKind: "unary";
    input: typeof ListTodosRequestSchema;
    output: typeof ListTodosResponseSchema;
  },
  /**
   * TODOアイテムを更新
   *
   * @generated from rpc todo.v1.TodoService.UpdateTodo
   */
  updateTodo: {
    methodKind: "unary";
    input: typeof UpdateTodoRequestSchema;
    output: typeof UpdateTodoResponseSchema;
  },
  /**
   * TODOアイテムを削除
   *
   * @generated from rpc todo.v1.TodoService.DeleteTodo
   */
  deleteTodo: {
    methodKind: "unary";
    input: typeof DeleteTodoRequestSchema;
    output: typeof DeleteTodoResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_todo_v1_todo, 0);